-- AlterTable
ALTER TABLE "AutoBid" ALTER COLUMN "max_price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "BidHistory" ALTER COLUMN "bid_price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "start_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "step_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "buy_now_price" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "current_price" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "final_price" SET DATA TYPE DOUBLE PRECISION;
